# Generated by Django 6.0.5 on 2026-05-10 17:35

import django.utils.timezone
import incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('road', 'Yo`l va trotuar'), ('lighting', 'Yoritish'), ('water', 'Suv ta`minoti'), ('electricity', 'Elektr'), ('sanitation', 'Tozalik'), ('other', 'Boshqa')], max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', 'O`rta'), ('high', 'Yuqori')], default='medium', max_length=16)),
                ('region', models.CharField(choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('andijon', 'Andijon'), ('fargona', 'Farg`ona'), ('namangan', 'Namangan'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm'), ('navoiy', 'Navoiy'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('qoraqalpogiston', 'Qoraqalpog`iston')], max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('IN_PROGRESS', 'Jarayonda'), ('RESOLVED', 'Hal qilindi'), ('CLOSED', 'Yopildi')], default='NEW', max_length=20)),
                ('workflow_round', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('initial', 'Boshlang`ich foto'), ('technician_completion', 'Texnik yakuniy foto'), ('operator_completion', 'Operator qo`shimcha foto')], max_length=32)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('image', models.FileField(upload_to=incidents.models.incident_photo_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('materials_used', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
