# Generated by Django 6.0.5 on 2026-05-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='citizen',
            field=models.ForeignKey(help_text='Citizen who reported the incident', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='users.citizen'),
        ),
        migrations.AddField(
            model_name='incident',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Operator responsible for this incident', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_incidents', to='users.operator'),
        ),
        migrations.AddField(
            model_name='incident',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Technician assigned to resolve this incident', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_incidents', to='users.technician'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incident_status_9427e5_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['category'], name='incident_categor_78f3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['priority'], name='incident_priorit_21ef78_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'priority'], name='incident_status_99d6b6_idx'),
        ),
    ]
