# Generated by Django 6.0.5 on 2026-05-10 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenfeedback',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizen_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technician_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entry', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentphoto',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentphoto',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentupdate',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentupdate',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='resolutionreport',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_reports', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='resolutionreport',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='resolutionreport',
            constraint=models.UniqueConstraint(fields=('incident', 'round_number'), name='unique_resolution_report_per_round'),
        ),
    ]
