# Generated by Django 6.0.5 on 2026-05-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='other_category_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('sanitation', 'Tozalik va chiqindi'), ('electricity', 'Elektr tarmoqlari'), ('water', 'Suv ta`minoti va quvurlar'), ('lighting', 'Ko`cha yoritish'), ('road', 'Yo`l va trotuar'), ('drainage', 'Kanalizatsiya va drenaj'), ('landscaping', 'Ko`kalamzorlashtirish va daraxtlar'), ('signal', 'Svetofor va xavfsizlik belgilari'), ('other', 'Boshqa')], max_length=32),
        ),
    ]
