# Generated by Django 6.0.5 on 2026-05-07 15:04

import django.db.models.deletion
import incidents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=incidents.models.incident_photo_path)),
                ('upload_type', models.CharField(choices=[('initial', 'Initial report'), ('completion', 'Completion report')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.incident')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_photo',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
