# Generated by Django 6.0.5 on 2026-05-11 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incidentphoto'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidents.incident')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_update',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detailed description of how the incident was resolved')),
                ('materials_used', models.TextField(blank=True, help_text='Optional: list of materials or equipment used')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the work was actually completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_report', to='incidents.incident')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_incidents', to='users.technician')),
            ],
            options={
                'db_table': 'resolution_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 (worst) to 5 (best)')),
                ('is_resolved', models.BooleanField(help_text='Citizen confirms if the incident was actually resolved')),
                ('reason', models.TextField(blank=True, help_text='If not resolved, the citizen must provide a reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_entries', to='users.citizen')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='incidents.incident')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'unique_together': {('incident', 'citizen')},
            },
        ),
    ]
